CSE_Academia/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.contrib.auth import views as auth_views



from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root' : settings.STATIC_ROOT }),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root' : settings.MEDIA_ROOT }),
    path('', views.Home.as_view(), name='home'),
    path('_notices/', include('noticeapp.urls')),
    path('_gallery/', include('galleryapp.urls')),
    path('_students/', include('students.urls')),
    path('_faculty/', include('Faculty_app.urls')),
    path('_alumni/', include('Alumni_app.urls')),



    path('_login/', views.Custom_loginview.as_view(), name='login'),
    path('_signup/', views.SignUpView.as_view(), name='signup'),
    path('_logout/', auth_views.LogoutView.as_view(), name='logout'),

] 

students/urls.py
from django.urls import path 
from . import views 

app_name = 'studentsapp'

urlpatterns = [
    path('ajax/skill-suggestions/', views.SkillSuggestionView.as_view(), name='skill-suggestions'),
    path('search_skills/', views.Search_skills.as_view(), name='search_skills'),
    path('all-students/', views.All_Students.as_view(), name='all_students'),
    path('profile/<slug:slug>/', views.Student_Profile.as_view(), name='student-profile'),
    path('update-profile/', views.Update_profile.as_view(), name='update_profile'),
    path('change-password/', views.Password_ChangeView.as_view(), name='change_password'),
    path('modify-certificates/', views.Delete_certificates.as_view(), name='modify_certificates'),
    path('search_blood/', views.Search_blood.as_view(), name='search_blood')
]

students/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class Student_Model(models.Model):
    photo = models.ImageField(upload_to='students_profile_pic', blank=True, null=True)
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    batch = models.IntegerField(blank=True, null=True)
    std_id = models.CharField(max_length=16)
    phone_number = models.CharField(max_length=11, blank=True, null=True)
    blood_group = models.CharField(max_length=3, blank=True, null=True)
    last_Blood_donated = models.DateField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    cv = models.FileField(upload_to='students_cv/', blank=True, null=True)
    skills = models.CharField(max_length=1000, blank=True, null=True)
    passion = models.CharField(max_length=1000, blank=True, null=True)

    whatsapp = models.CharField(max_length=11, blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    google_scholar = models.URLField(blank=True, null=True)
    gmail = models.EmailField(blank=True, null=True)

    slug = models.SlugField(unique=True)

    class Meta():
        ordering = ['-batch', 'std_id']
        verbose_name= 'Student Info'

    def __str__(self):
        return f'{self.batch}th batch | {self.name} | id: {self.std_id}'


class Certificate_Photo(models.Model):
    profile = models.ForeignKey(Student_Model, related_name='certificates', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='students_certificates', blank=True, null=True)
    upload_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.profile.batch}th batch | {self.profile.std_id} | {self.profile.name}'
    
    class Meta():
        verbose_name_plural = 'Student Certificates'
        ordering = ['profile__batch', 'profile__std_id', '-upload_date']


class Thumbnail_photo(models.Model):
    profile = models.OneToOneField(Student_Model, related_name='thumbnail', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='thumbnails', blank=True, null=True)
    
    def __str__(self):
        return f'{self.profile.user.username}'
    
    class Meta():
        ordering = ['-pk']

students/forms.py
from django import forms 
from django.core.validators import FileExtensionValidator
import base64
from django.core.files.base import ContentFile
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys

from .models import Student_Model, Certificate_Photo, Thumbnail_photo



# Custom widget for handling multiple file uploads
class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        if isinstance(data, (list, tuple)):
            return [super(MultipleFileField, self).clean(d) for d in data]
        return [super().clean(data)]




class Update_student_profile(forms.ModelForm):

    class Meta:
        model = Student_Model
        exclude = ['user', 'slug'] 

    BLOOD_GROUP_CHOICES = [
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
    ]

    blood_group = forms.ChoiceField(
        choices=BLOOD_GROUP_CHOICES,  # Define the choices here
        widget=forms.RadioSelect()  # Use RadioSelect to render as radio buttons
    )

    last_Blood_donated = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={
            'type': 'date',  # This makes it display as a date picker in modern browsers
            'placeholder': 'Select a date'
        })
    )

    images = MultipleFileField(required=False, label='Upload all your Certificate photos')  # Use custom MultipleFileField # extra added
    cv_clear = forms.BooleanField(required=False, label='Clear CV', help_text="Check this to remove the existing CV")  # extra added

    batch = forms.IntegerField()
    description = forms.CharField(required=False, label='About yourself', widget=forms.Textarea())
    cv = forms.FileField(required=False, label='Your CV (curiculam vita)', validators=[FileExtensionValidator(allowed_extensions=['pdf'])],
                          widget=forms.FileInput(attrs={'accept': 'application/pdf'}))
    
    skills = forms.CharField(required=False, label='Seperate your skill tags using comma , ', widget=forms.Textarea(attrs={'rows':5, 'placeholder': 'fontend, backend, javascript, html, css, tailwind, bootstrap, graphics design, video editor, node-js, singer, photographer, hacking, volunteer, etc.'}))

    passion = forms.CharField(required=False, label='Seperate your passion tags using comma , ', widget=forms.Textarea(attrs={'rows':5, 'placeholder': 'programming, hacking, singing, danching, acting, travelling, volunteering etc.'}))


    def save(self, commit=True):
        instance = super().save(commit=False)

        


        # Handle clearing CV file if necessary
        if self.cleaned_data.get('cv_clear') and instance.cv:
            instance.cv.delete()

        if commit:
            instance.save()

            # process Profile picture
            profile_pic = self.data.get('cropped_image', '')  # can't use cleaned_data.get() cz this field is not in form class rather extra added in 'template file'
            if profile_pic:
                format, imgstr = profile_pic.split(';base64,')
                ext = format.split('/')[-1]
                image_data = ContentFile(base64.b64decode(imgstr), name=f'profile_pic.{ext}')
                instance.photo = image_data
                instance.save()  # save again to update changes

                ti = Thumbnail_photo.objects.filter(profile=instance)
                if ti.exists():
                    thumbnail = ti.first()

                    img = Image.open(image_data)
                    img = img.resize((100, 100), Image.LANCZOS)  
                    buffer = BytesIO()
                    img.save(buffer, format=ext.upper())
                    compressed_image_data = ContentFile(buffer.getvalue(), name=f'thumbnail_compressed.{ext}')

                    thumbnail.image = compressed_image_data 
                    thumbnail.save()
            else:
                profile_pic = self.data.get('uncropped_but_compressed', '')
                if profile_pic:
                    format, imgstr = profile_pic.split(';base64,')
                    ext = format.split('/')[-1]
                    image_data = ContentFile(base64.b64decode(imgstr), name=f'profile_pic.{ext}')
                    instance.photo = image_data
                    instance.save()  # save again to update changes

                    ti = Thumbnail_photo.objects.filter(profile=instance)
                    if ti.exists():
                        thumbnail = ti.first()

                        img = Image.open(image_data)
                        img = img.resize((100, 100), Image.LANCZOS)  
                        buffer = BytesIO()
                        img.save(buffer, format=ext.upper())
                        compressed_image_data = ContentFile(buffer.getvalue(), name=f'thumbnail_compressed.{ext}')

                        thumbnail.image = compressed_image_data 
                        thumbnail.save()
            
            print('certificate images = ', self.files)

            # process Certificate Images
            compressed_images = self.data.getlist('certificate_images[]')   # can't use cleaned_data.get() cz this field is not in form class rather extra added in 'template file'
            for base64_image in compressed_images:
                # Convert the base64 string back to image
                format, imgstr = base64_image.split(';base64,')  # split the format and base64 string
                ext = format.split('/')[-1]  # extract file extension from format
                image_data = ContentFile(base64.b64decode(imgstr), name=f'certificate_image.{ext}')
                
                # Create and save the Certificate_Photo object with the compressed image
                Certificate_Photo.objects.create(profile=instance, image=image_data)


            #process Thubmnail image

        return instance

students/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DetailView, ListView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.contrib.auth.views import PasswordChangeView
from collections import defaultdict
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import JsonResponse

from .models import Student_Model, Certificate_Photo
from .forms import Update_student_profile

# Create your views here.

class Password_ChangeView(PasswordChangeView):
    template_name = 'change_password.html'
    
    def get_success_url(self):
        slug = self.request.user.profile.slug
        return reverse_lazy('studentsapp:student-profile', kwargs={'slug': slug})

class Search_skills(ListView):
    model = Student_Model
    template_name = 'search_skills.html'
    context_object_name = 'students'
    paginate_by = 20

    def get_queryset(self):
        key = self.request.GET.get('skill', '')
        if key:
            return Student_Model.objects.filter(
                Q(skills__icontains=key) | Q(passion__icontains=key)
            )
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('skill', '')
        return context



class SkillSuggestionView(View):
    def get(self, request, *args, **kwargs):
        query = request.GET.get('skill', '').lower()
        if query:
            # Fetch distinct skill sets from both 'skills' and 'passion' fields
            students = Student_Model.objects.filter(
                Q(skills__icontains=query) | Q(passion__icontains=query)
            ).values_list('skills', 'passion').distinct()

            matched_skills = []
            for skills, passion in students:
                # Split both 'skills' and 'passion' fields by commas and filter
                skill_list = [skill.strip() for skill in (skills or '').split(',')]
                passion_list = [passion.strip() for passion in (passion or '').split(',')]
                
                # Append skills that start with the query
                for skill in skill_list:
                    # if skill.lower().startswith(query):
                    if query in skill.lower(): 
                        matched_skills.append(skill)
                
                # Append passion that start with the query
                for passion in passion_list:
                    # if passion.lower().startswith(query):
                    if query in passion.lower(): 
                        matched_skills.append(passion)
                
                # Stop if we already have 10 suggestions
                # if len(matched_skills) >= 10:
                #     break

            return JsonResponse(matched_skills[:7], safe=False)
        
        return JsonResponse([], safe=False)





class All_Students(ListView):
    model = Student_Model
    template_name = 'all_students.html'
    context_object_name = 'students_by_batch'
    paginate_by = 40

    def get_queryset(self):
        # Get the search query from the GET request
        std_name = self.request.GET.get('search', '')

        # If search query exists, filter students based on the search query
        if std_name:
            return Student_Model.objects.filter(Q(name__icontains=std_name) | Q(batch__icontains=std_name)).order_by('-batch', 'std_id')
        
        # If no search query, return all students ordered by batch and std_id
        return Student_Model.objects.order_by('-batch', 'std_id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Group students by batch
        grouped_students = defaultdict(list)
        for student in context['students_by_batch']:
            grouped_students[student.batch].append(student)

        # Add grouped students to context
        context['grouped_students'] = dict(grouped_students)

        # Pass the search query to the template
        context['search_query'] = self.request.GET.get('search', '')
        
        return context




class Student_Profile(DetailView):
    model = Student_Model
    context_object_name = 'profile'
    template_name = 'student_profile.html'
    paginate_by = 3  # Number of images per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Get the student's certificates/photos
        images = Certificate_Photo.objects.filter(profile=self.object)

        # Add pagination for the images
        paginator = Paginator(images, self.paginate_by)
        page_number = self.request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)

        context['page_obj'] = page_obj
        context['is_paginated'] = page_obj.has_other_pages()
        
        return context

    def post(self, request, *args, **kwargs):
        """Handles AJAX request for loading more images."""
        profile = self.get_object()
        page = int(request.POST.get('page', 1))

        images = Certificate_Photo.objects.filter(profile=profile)
        paginator = Paginator(images, self.paginate_by)
        page_obj = paginator.get_page(page)

        image_urls = [image.image.url for image in page_obj]
        has_next = page_obj.has_next()

        return JsonResponse({
            'image_list': image_urls,
            'has_next': has_next
        })


class Update_profile(LoginRequiredMixin, UpdateView):
    model = Student_Model
    form_class = Update_student_profile
    template_name = 'update_student_profile.html'

    def get_success_url(self):
        return reverse_lazy('studentsapp:student-profile', kwargs={'slug': self.request.user.profile.slug})

    def get_object(self, queryset=None):
        return get_object_or_404(Student_Model, user=self.request.user)




class  Delete_certificates(View):
    def get(self, request):
        obj = Student_Model.objects.get(user = request.user)
        return render(request, 'delete_certificates.html', {'obj': obj})
    
    def post(self, request):
        # Get selected certificate IDs from the POST request
        selected_certificates = request.POST.getlist('certificates')

        if selected_certificates:
            # Delete the selected certificates
            Certificate_Photo.objects.filter(id__in=selected_certificates).delete()

        return redirect(reverse_lazy('studentsapp:student-profile', kwargs={'slug': request.user.profile.slug }))


class Search_blood(ListView):
    model = Student_Model
    template_name = 'search_blood.html'
    context_object_name = 'students'
    paginate_by = 15  

    def get_queryset(self):
        query = self.request.GET.get('q')  # Get the search term from the request
        if query:
            return Student_Model.objects.filter(blood_group=query)
        return Student_Model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('q', '')  # Add search query to context
        return context

students/templates/all_students.html
{% extends 'base.html' %} {% load static %}
{% block title %} Members of CSE Academia{% endblock %}
{% block main_tag_style %} {% endblock %}
{% block body %}



<div class="search_students">
    <form action="" method="GET" class="form flex flex-row space-x-3 md:w-2/3 lg:w-1/2 md:mx-auto mx-2 my-10 p-5 md:p-10 shadow-xl rounded-lg bg-gray-100">
        <input type="search" name="search" id="search_students" value="{{ search_query }}" class="form-control p-2 w-full rounded-lg outline-none focus:ring-2 focus:ring-orange-500 transition duration-300 ease-in-out" placeholder="Search students by name">
        <button type="submit" class="btn bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-orange-500 transition duration-300 ease-in-out">Search</button>
    </form>
</div>

<!-- {{ grouped_students }} -->
<div class="md:w-2/3 lg:w-1/2 md:mx-auto mx-2 my-10 p-5 md:p-10 shadow-xl rounded-lg bg-gray-100">
    {% for batch, students in grouped_students.items %}
        {% if batch == None %}
            <div class="p-2 py-6 mb-2 font-medium text-center text-gray-600 rounded-lg bg-orange-200 outline outline-2 outline-teal-800">
                These students haven't updated their profile yet.
            </div>
            {% for student in students %}
                <a href="{% url 'studentsapp:student-profile' slug=student.slug %}">
                    <div class="flex align-items-center space-x-3 p-2 mb-2 font-medium text-gray-900 bg-gray-400 rounded-lg shadow-inner transform duration-300 hover:scale-105 hover:bg-orange-300">
                        <span class="inline-block h-[40px] w-[40px] shrink-0 rounded-full overflow-hidden mr-3">
                            <img src="{% if student.thumbnail.image %}{{ student.thumbnail.image.url }} {% else %} {% static 'images/profile_sm.png' %} {% endif %}" alt="Profile Image">
                        </span>
                        <span>{{ student }}</span>
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <div class="p-2 py-6 mb-2 font-medium text-center text-gray-600 rounded-lg bg-orange-200 outline outline-2 outline-teal-800">{{ batch }}th Batch | {{ students|length }} students</div>
            {% for student in students %}
                <a href="{% url 'studentsapp:student-profile' slug=student.slug %}">
                    <div class="flex align-items-center space-x-3 p-2 mb-2 font-medium text-gray-900 bg-gray-300 rounded-lg shadow-inner transform duration-300 hover:scale-105 hover:bg-orange-300">
                        <span class="inline-block h-[40px] w-[40px] shrink-0 rounded-full overflow-hidden mr-3">
                            <img src="{% if student.thumbnail.image %}{{ student.thumbnail.image.url }} {% else %} {% static 'images/profile_sm.png' %} {% endif %}" alt="Profile Image">
                        </span>
                        <span>{{ student }}</span>
                    </div>
                </a>
            {% endfor %}
        {% endif %}
    {% empty %}
        <li>No batches found.</li>
    {% endfor %}
</div>

<!-- Pagination -->
<nav class="my-10">
    <ul class="pagination w-fit mx-auto shadow-lg space-x-2">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link bg-green-500 text-white px-3 py-1 rounded-lg hover:bg-orange-500 transition duration-300" href="?page=1">&laquo; First</a>
            </li>
            <li class="page-item">
                <a class="page-link bg-green-500 text-white px-3 py-1 rounded-lg hover:bg-orange-500 transition duration-300" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
        {% endif %}
        
        <li class="page-item">
            <span class="page-link bg-blue-500 text-white px-3 py-1 rounded-lg">Page {{ page_obj.number }} of {{ paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link bg-green-500 text-white px-3 py-1 rounded-lg hover:bg-orange-500 transition duration-300" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link bg-green-500 text-white px-3 py-1 rounded-lg hover:bg-orange-500 transition duration-300" href="?page={{ paginator.num_pages }}">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav>





{% endblock %}

students/templates/change_password.html
{% extends 'base.html' %} {% load crispy_forms_tags %}
{% block title %} Update Password {% endblock %}
{% block main_tag_style %} {% endblock %}
{% block body %}

<div class="md:w-1/2 md:mx-auto mx-2 my-10 md:p-10 p-2 rounded-lg shadow-md">
    
    <form class="flex flex-col max-w-sm mx-auto mb-5" method="POST"> {% csrf_token %}

        {{ form | crispy }}
        <button type="submit" class="btn btn-success  my-4">Update</button>
    </form>
  
  
  
    
</div>


        
{% endblock %}

students/templates/delete_certificates.html
{% extends 'base.html' %}

{% block title %}{{ obj.name }}'s Profile{% endblock %}

{% block body %}

<div class="container my-10">
    <form method="post" action="">
        {% csrf_token %}
        {% for img in obj.certificates.all %}
            <div class="image-item">
                <input type="checkbox" name="certificates" value="{{ img.id }}">
                <img src="{{ img.image.url }}" alt="" width="100px" height="100px">
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-danger mt-5">Delete Selected</button>
    </form>
</div>



{% endblock %}
{% block script %}
<script>

</script>
{% endblock %}

students/templates/search_skills.html
{% extends 'base.html' %}   {% load static %}
{% block title %} Search Skills {% endblock %}
{% block main_tag_style %}
<style>
#suggestions div {
    padding: 8px;
    cursor: pointer;
}

#suggestions div:hover {
    background-color: #f3f4f6;
}
#suggestions {
    display: block !important;  /* Force it to be shown when necessary */
    position: absolute;
    width: 100%;
    background-color: white;
    border: 1px solid #ccc;
    z-index: 1000;
}
</style>
{% endblock %}
{% block body %}

<div class="md:w-1/2 md:mx-auto mx-2 my-10 md:p-10 p-2 rounded-lg shadow-md">
    
    <form class="flex flex-col max-w-sm mx-auto mb-5" method="GET">
        <div>
            <label for="small-input" class="block mb-2 text-sm font-medium text-gray-900">
                Search skills e.g. python, css, backend, hacking, design
            </label>
            <input type="text" id="skill-input" name="skill" class="form-control" value="{{ search_query }}" placeholder="python" autocomplete="off">
            <div id="suggestions" class="bg-white border border-gray-200 rounded-md shadow-lg mt-2 absolute z-10"></div>
        </div>
        <button type="submit" class="btn btn-success my-4">Search</button>
    </form>

        {% for std in students %}
            <a href="{% url 'studentsapp:student-profile' slug=std.slug %}">
                <div class="flex align-items-center space-x-3 p-2 my-4 rounded-t-lg bg-gray-300 shadow-lg font-semibold text-gray-700">
                    <span class="inline-block h-[40px] w-[40px] shrink-0">
                        <img class="w-full h-full rounded-full" src="{% if std.thumbnail.image %}{{ std.thumbnail.image.url }} {% else %} {% static 'images/profile_sm.png' %} {% endif %}" alt="">
                    </span>
                    <span>{{ std.batch }}th batch | {{ std.name }} | id: {{ std.std_id }}</span>
                </div>
                <div class="bg-gray-200 mt-[-16px] p-5 rounded-b-lg font-medium text-teal-800">
                    <div>
                        <strong class="text-sky-500">Skills:</strong> <span class="highlight">{{ std.skills|default:"No skills listed." }}</span>
                    </div>
                    <div>
                        <strong class="text-sky-500">Passion:</strong> <span class="highlight">{{ std.passion|default:"No passion listed." }}</span>
                    </div>
                </div>
            </a>
        {% empty %}
            <div class="p-2 my-4 rounded-t-lg bg-gray-200 shadow-lg font-medium text-lg text-red-500 text-center">No match found.</div>
        {% endfor %}

    
        <script>
            $(document).ready(function () {
                $('#skill-input').on('input', function (e) {
                    e.preventDefault();  // Prevent form submission
                    const searchKeyword = $(this).val();
                    if (searchKeyword.length > 0) {
                        $.ajax({
                            url: "{% url 'studentsapp:skill-suggestions' %}",
                            data: {
                                'skill': searchKeyword
                            },
                            success: function (data) {
                                let suggestionsBox = $('#suggestions');
                                suggestionsBox.empty().show();
                                if (data.length > 0) {
                                    data.forEach(suggestion => {
                                        // Highlight the matching part of the skill or passion
                                        const regex = new RegExp("(" + searchKeyword + ")", "gi");
                                        const highlightedSuggestion = suggestion.replace(regex, "<span class='bg-yellow-300'>$1</span>");
                                        suggestionsBox.append(`<div class="p-2 cursor-pointer hover:bg-gray-200">${highlightedSuggestion}</div>`);
                                    });
                                } else {
                                    suggestionsBox.hide();
                                }
                            },
                            error: function () {
                                console.error("An error occurred while fetching suggestions.");
                            }
                        });
                    } else {
                        $('#suggestions').hide();
                    }
                });

                // Handling dropdown item click
                $('#suggestions').on('click', 'div', function () {
                    $('#skill-input').val($(this).text());
                    $('#suggestions').hide();
                });


                        // Highlight the search result
                const searchKeyword = "{{ request.GET.skill }}".trim().toLowerCase();
                if (searchKeyword !== "") {
                    $('.highlight').each(function () {
                        let content = $(this).html();
                        let regex = new RegExp("(" + searchKeyword + ")", "gi");
                        let highlightedContent = content.replace(regex, "<span class='bg-yellow-300'>$1</span>");
                        $(this).html(highlightedContent);
                    });
                }
            });


        </script>
  
    
</div>


                    <!-- ------ Pagination -----  -->

<!-- <nav class="my-10">
    <ul class="pagination w-fit mx-auto shadow-lg">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        
        <li class="page-item"><a class="page-link text-bg-primary" href="#">Page {{ page_obj.number }} of {{ paginator.num_pages }}.</a></li>

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
    </ul>
</nav> -->


<!-- Pagination -->
<nav class="my-10">
    <ul class="pagination w-fit mx-auto shadow-lg space-x-2">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link bg-green-500 text-white px-3 py-1 rounded-lg hover:bg-orange-500 transition duration-300" href="?page=1">&laquo; First</a>
            </li>
            <li class="page-item">
                <a class="page-link bg-green-500 text-white px-3 py-1 rounded-lg hover:bg-orange-500 transition duration-300" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
        {% endif %}
        
        <li class="page-item">
            <span class="page-link bg-blue-500 text-white px-3 py-1 rounded-lg">Page {{ page_obj.number }} of {{ paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link bg-green-500 text-white px-3 py-1 rounded-lg hover:bg-orange-500 transition duration-300" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link bg-green-500 text-white px-3 py-1 rounded-lg hover:bg-orange-500 transition duration-300" href="?page={{ paginator.num_pages }}">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}