Alumni_app/urls.py
from django.urls import path 
from . import views

app_name = 'Alumni_app'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

CSE_Academia/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.contrib.auth import views as auth_views



from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root' : settings.STATIC_ROOT }),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root' : settings.MEDIA_ROOT }),
    path('', views.Home.as_view(), name='home'),
    path('_notices/', include('noticeapp.urls')),
    path('_gallery/', include('galleryapp.urls')),
    path('_students/', include('students.urls')),
    path('_faculty/', include('Faculty_app.urls')),
    path('_alumni/', include('Alumni_app.urls')),



    path('_login/', views.Custom_loginview.as_view(), name='login'),
    path('_signup/', views.SignUpView.as_view(), name='signup'),
    path('_logout/', auth_views.LogoutView.as_view(), name='logout'),

] 

galleryapp/urls.py
from django.urls import path 
from . import views 


app_name = 'galleryapp'

urlpatterns = [
    path('list-activity/', views.List_activity.as_view(), name='list_activity'),
    path('<slug:slug>/', views.ActivityGallary.as_view(), name='activity-gallery'),
    path('cla/', views.RoutineView.as_view(), name='cla'),
]

noticeapp/urls.py
from django.urls import path 
from . import views 

app_name = 'noticeapp'


urlpatterns = [
    path('', views.All_notice.as_view(), name='all_notice'),
    path('notice/<slug:slug>/', views.NoticeView.as_view(), name='notice'),
    path('class-routine/', views.RoutineView.as_view(), name='class-routine'),
    path('course-content/', views.Course_content.as_view(), name='course_content'),
]

students/urls.py
from django.urls import path 
from . import views 

app_name = 'studentsapp'

urlpatterns = [
    path('ajax/skill-suggestions/', views.SkillSuggestionView.as_view(), name='skill-suggestions'),
    path('search_skills/', views.Search_skills.as_view(), name='search_skills'),
    path('all-students/', views.All_Students.as_view(), name='all_students'),
    path('profile/<slug:slug>/', views.Student_Profile.as_view(), name='student-profile'),
    path('update-profile/', views.Update_profile.as_view(), name='update_profile'),
    path('change-password/', views.Password_ChangeView.as_view(), name='change_password'),
    path('modify-certificates/', views.Delete_certificates.as_view(), name='modify_certificates'),
    path('search_blood/', views.Search_blood.as_view(), name='search_blood')
]

Alumni_app/models.py
from django.db import models

# Create your models here.

Alumni_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class HomeView(TemplateView):
    template_name = 'alumni/home.html'

Alumni_app/templates/alumni/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- <meta http-equiv="refresh" content="1"> -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>{% block title %}{{ title }} {% endblock %} | CSE Academia</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'src/aos/aos.css' %}">
    <link rel="stylesheet" href="{% static 'src/css/tailwind/output.css' %}">



    <script src="{% static 'src/js/jquery.js' %}"></script>


    {% block style %} {% endblock %}
    {% block script_head %} {% endblock %}

  <style>
    html, body {
        height: 100%;
        margin: 0;
    }
    body {
        display: flex;
        flex-direction: column;
    }
    main {
        flex: 1;
    }



/*   my custom animations  */
/* Slide-up animation */
@keyframes slideUp {
  0% {
    top : 80px;
    opacity: 0;
  }
  100% {
    top : 44px;
    opacity: 1;
  }
}

/* Slide-up animation class */
.my_slideUp {
  animation: slideUp 0.3s ease-out forwards;
  opacity: 0; /* Ensure it's initially invisible */
}
.dropdown_arrow::after {
  display: inline-block;
  margin-left: .255em;
  vertical-align: .255em;
  content: "";
  border-top: .3em solid;
  border-right: .3em solid transparent;
  border-bottom: 0;
  border-left: .3em solid transparent;
}

.navbar .nav-link {
    margin-right: 10px;
    background: none;
    /* box-shadow: inset 0 0 5px rgba(249, 115, 22, 0.4), rgba(255, 255, 255, 0.1) 0 1px 0; */
    border-radius: 4px;
    border: 1px solid transparent;
    padding: 8px;
    /* color: #fff !important; */
    color : rgb(249 115 22) !important;
    /* text-shadow: rgba(0, 0, 0, 0.796875) 0 -1px 0, rgba(255, 255, 255, 0.296875) 0 0 10px; */
}

.navbar .nav-link:hover{
  background-color: rgb(249 115 22);
  color: #fff !important;
}


</style>

</head>
<body id="body">


  <nav class="navbar p-0 navbar-expand-lg bg-body-tertiary fixed-top  shadow-lg">
    <div class="container-fluid">
      <!-- logo -->
      <a class="navbar-brand p-0" href="/">
        <img src="{% static 'icons/kyau-logo.jpg' %}" class="w-12 h-12 inline-block me-3 rounded-full" alt="CSE Academia">
        <!-- <h1 class="relative text-2xl font-medium z-10 inline-block text-transparent bg-clip-text bg-gradient-to-r from-pink-400 to-white animate-gradient-header-brand"> -->
        <h1 class="nav-logo relative text-2xl font-medium z-10 inline-block text-green-700">
          CSE Academia
        </h1>
      </a>
      

      <!-- collasp button  -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- menu items -->
      <div class="collapse navbar-collapse max-h-[400px] overflow-y-scroll  b-lg:overflow-y-visible" style="visibility: visible !important;" id="navbarNavDropdown">
        <div class="navbar-nav mx-auto">
          <span class="underline-width-animate">
            <a class="nav-link  text-lg  font-normal" aria-current="page" href="{% url 'Alumni_app:home' %}">Home</a>
          </span>
        </div>
      </div>
    </div>
  </nav>





<script>
   $('.navbar-nav .nav-link').addClass('active text-green-700');
  
  // dropdown-menu toggling
  if ( window.innerWidth > 991){
    $('.navbar .underline-width-animate').on('mouseenter', function(){
      $(this).find('.dropdown-menu').show();
    });
    $('.navbar .underline-width-animate').on('mouseleave', function(){
      $(this).find('.dropdown-menu').hide();
    });
  } else { // apply click event on small screens
    $('.navbar .underline-width-animate').on('click', function() {
    var $dropdownMenu = $(this).find('.dropdown-menu');
    
    $dropdownMenu.addClass('absolute w-full').toggle();

    if ($dropdownMenu.is(':visible')) {
      var dropdownHeight = $dropdownMenu.outerHeight();

      // Apply margin to the subsequent elements to accommodate dropdown's height
      $(this).next().css('margin-top', dropdownHeight + 'px');
    } else {
      // Reset the margin when the dropdown is hidden
      $(this).next().css('margin-top', 0);
    }
  });

  }
  

  

</script>



      <main class="mt-[48px] {% block main_tag_style %}{%endblock%}">

        {% if messages %}
          <div class="messages">
              {% for message in messages %}
                  <p class="alert alert-{{ message.tags }}">{{ message }}</p>
              {% endfor %}
          </div>
        {% endif %}

        {% block body %} {% endblock %}


    </main>





        <footer class="bg-zinc-800 text-white py-8">
            <div class="container mx-auto px-4">
              <div class="flex flex-wrap justify-between">
                <!-- About Section -->
                <div class="w-full md:w-1/3 lg:w-1/4 mb-6 md:px-5">
                  <h5 class="font-bold text-lg mb-4">CSE Academia</h5>
                  <p class="text-gray-400">We are a community of tech enthusiasts aiming to explore, innovate, and share knowledge in the field of computer science and technology.</p>
                </div>

                <!-- Quick Links -->
                <div class="w-full md:w-1/3 lg:w-1/4 mb-6">
                  <h5 class="font-bold text-lg mb-4">Quick Links</h5>
                  <ul class="list-none">
                    <li><a href="/" class="text-gray-400 hover:text-gray-100">Home</a></li>
                    <li><a href="{% url 'noticeapp:all_notice' %}" class="text-gray-400 hover:text-gray-100">Notices</a></li>
                    <li><a href="{% url 'galleryapp:list_activity' %}" class="text-gray-400 hover:text-gray-100">Activity</a></li>
                    <li><a href="{% url 'studentsapp:all_students' %}" class="text-gray-400 hover:text-gray-100">All Students</a></li>
                    <li><a href="{% url 'studentsapp:search_skills' %}" class="text-gray-400 hover:text-gray-100">Search skills</a></li>
                  </ul>
                </div>

                <!-- Developer section -->
                <div class="w-full md:w-1/3 lg:w-1/4 mb-6">
                  <div class="space-y-4">
                    <h2 class="text-xl font-semibold text-white">Developer</h2>
                    <div class="flex items-center space-x-4">
                        <a href="{% url 'studentsapp:student-profile' slug='137d1e1f-ca10-494c-81ac-5fbc32ac712b' %}" target="_blank" class="hover:scale-[1.5] duration-300">
                          <img class="w-16 h-16 rounded-full border-4 border-white object-cover" src="{% static 'images/developer.jpg' %}" alt="Developer Profile">
                        </a>
                        <div>
                            <h3 class="text-lg font-semibold text-sky-400">Md. AL-Imran Sarker</h3>
                            <p class="text-gray-400">Software Developer</p>
                            <a href="https://www.facebook.com/itsimransarker" class="text-indigo-500 hover:underline hover:text-indigo-600" target="_blank">LinkedIn Profile</a>
                        </div>
                    </div>
                    <div class="flex items-center space-x-3 mt-4">
                        <img src="{% static 'icons/telephone.png' %}" class="w-5 h-5" alt="Phone Icon">
                        <span class="text-green-400">01791-115371</span>
                    </div>
                    <div class="flex items-center space-x-3">
                        <img src="{% static 'icons/email-opened.png' %}" class="w-5 h-5" alt="Email Icon">
                        <span class="text-green-400">imranthelegend12@gmail.com</span>
                    </div>
                  </div>
                </div>
                <!-- Contact Section -->
                <div class="w-full md:w-1/3 lg:w-1/4 mb-6">
                  <h5 class="font-bold text-lg mb-4">Get in Touch</h5>
                  <ul class="list-none text-gray-400">
                    <li>Email: info@cseacademia.com</li>
                    <li>Phone: 01791-115371</li>
                    <li>Location: KYAU, Enayetpur, Sirajganj</li>
                  </ul>
                  <div class="flex mt-4 space-x-4">
                    <!-- Social Icons -->
                    <a href="https://www.facebook.com/groups/1622534417999961" target="_blank" class="text-gray-400 hover:text-gray-100">
                      <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M22.23 0H1.77C.79 0 0 .79 0 1.77v20.46C0 23.21.79 24 1.77 24h11v-9.29h-3v-3.62h3V8.41c0-3.1 1.9-4.79 4.67-4.79 1.33 0 2.48.1 2.82.14v3.27l-1.94.001c-1.52 0-1.81.72-1.81 1.77v2.32h3.62l-.47 3.62h-3.15V24h6.17C23.21 24 24 23.21 24 22.23V1.77C24 .79 23.21 0 22.23 0z"/></svg>
                    </a>
                    <a href="#" class="text-gray-400 hover:text-gray-100">
                      <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M24 4.56v14.88C24 22.15 22.15 24 19.44 24H4.56C1.85 24 0 22.15 0 19.44V4.56C0 1.85 1.85 0 4.56 0h14.88C22.15 0 24 1.85 24 4.56zm-4.23 1.64c-.41-.41-.99-.67-1.64-.67-.64 0-1.23.26-1.64.67-.41.41-.67.99-.67 1.64 0 .64.26 1.23.67 1.64.41.41.99.67 1.64.67.64 0 1.23-.26 1.64-.67.41-.41.67-.99.67-1.64 0-.64-.26-1.23-.67-1.64zM12 6.93c-2.82 0-5.07 2.25-5.07 5.07 0 .42.05.82.13 1.21l-3.55-.15c-.29 0-.53.24-.53.53v.59c0 .29.24.53.53.53h3.55c-.09.39-.14.79-.14 1.21 0 2.82 2.25 5.07 5.07 5.07 2.82 0 5.07-2.25 5.07-5.07 0-2.82-2.25-5.07-5.07-5.07zm0 8.64c-1.97 0-3.57-1.6-3.57-3.57 0-.69.19-1.33.53-1.88l.15-.21h3.82c.37.57.58 1.22.58 1.88 0 1.97-1.6 3.57-3.57 3.57zm5.44-2.57l-.53-.59c-.09-.09-.21-.14-.32-.14-.29 0-.53.24-.53.53v.59c0 .29.24.53.53.53.11 0 .23-.05.32-.14l.53-.59c.09-.09.14-.21.14-.32s-.05-.23-.14-.32z"/></svg>
                    </a>
                    <a href="#" class="text-gray-400 hover:text-gray-100">
                      <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M12 0C5.37 0 0 5.37 0 12c0 5.37 3.43 9.91 8.2 11.43.6.11.82-.26.82-.58 0-.29-.01-1.26-.01-2.3-3.34.63-4.04-1.42-4.04-1.42-.55-1.41-1.35-1.79-1.35-1.79-1.1-.76.08-.74.08-.74 1.21.09 1.85 1.24 1.85 1.24 1.08 1.85 2.82 1.32 3.51 1.01.11-.78.42-1.32.76-1.62-2.67-.31-5.47-1.34-5.47-5.98 0-1.32.47-2.39 1.24-3.23-.12-.31-.54-1.56.12-3.25 0 0 1.01-.32 3.31 1.24a11.5 11.5 0 0 1 3.01-.4c1.02 0 2.05.13 3.01.4 2.29-1.56 3.31-1.24 3.31-1.24.66 1.69.24 2.94.12 3.25.77.84 1.24 1.91 1.24 3.23 0 4.65-2.8 5.67-5.48 5.98.43.37.82 1.1.82 2.22 0 1.6-.01 2.89-.01 3.29 0 .33.22.69.82.58C20.57 21.91 24 17.37 24 12c0-6.63-5.37-12-12-12z"/></svg>
                    </a>
                  </div>
                </div>
              </div>
              <!-- Footer Bottom -->
              <div class="mt-8 border-t border-gray-700 pt-4">
                <p class="text-center text-gray-500">© 2024 CSE Academia. All rights reserved.</p>
              </div>
            </div>
          </footer>


            <!--   ---------   All Script tags ----------    -->

    <script src="{% static 'src/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'src/aos/aos.js' %}"></script>
    <script src="{% static 'src/js/custom.js' %}"></script>

    {% block script %} {% endblock %}

    <script>
      $('.main-navbar').on('click', '.menu-item', function(e) {
        $('.main-navbar .submenu').not($(this).next()).addClass('hidden');
        $($(this)).next().toggleClass('hidden');
      });

      // Initialize animate on scroll js library
        AOS.init();
    </script>

</body>
</html>

Alumni_app/templates/alumni/home.html
{% extends 'alumni/base.html' %} {% load static %}

<title>{% block title %} Alumni {{ title }} {% endblock %}</title>

{% block style %}
{% endblock %}
{% block script_head %} {% endblock %}
{% block body %}

<div class="bg-gray-300 py-5 text-xl sm:text-3xl font-semibold text-center text-sky-600">Meet the Alumni</div>

<section class="alumni-section my-10">

  <form action="" class="w-full md:w-1/2 mx-auto flex space-x-2 p-2">
    <input type="text" class="form-control border-1 border-sky-600" name="" id="" placeholder="Search Name">
    <input type="submit" value="Search Alumni" class="btn btn-outline-success">
  </form>


  <div class="w-full md:w-2/3 alumni-list mt-10 flex flex-wrap justify-center space-x-8 space-y-14 mx-auto">

    <div class="alumni w-1/5 ml-8 mt-14 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <div class="alumni w-1/5 rounded-lg border-1 border-gray-300 cursor-pointer">
      <div class="wrapper overflow-hidden">
        <img src="{% static 'images/alumni_default.png' %}" alt="" class="duration-300">
      </div>
      <div class="alumni_name pl-2 pt-1 text-center text-lg text-sky-600 font-medium">Md. Abu Saleh</div>
      <div class="alumni_status pl-2 text-center text-green-700">Assistant Professor</div>
    </div>
    
    <style>.alumni:hover img{scale: 1.1;}</style>
  </div>

</section>

{% endblock %}