CSE_Academia/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.contrib.auth import views as auth_views



from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root' : settings.STATIC_ROOT }),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root' : settings.MEDIA_ROOT }),
    path('', views.Home.as_view(), name='home'),
    path('_notices/', include('noticeapp.urls')),
    path('_gallery/', include('galleryapp.urls')),
    path('_students/', include('students.urls')),
    path('_faculty/', include('Faculty_app.urls')),
    path('_alumni/', include('Alumni_app.urls')),



    path('_login/', views.Custom_loginview.as_view(), name='login'),
    path('_signup/', views.SignUpView.as_view(), name='signup'),
    path('_logout/', auth_views.LogoutView.as_view(), name='logout'),

] 

Faculty_app/urls.py
from django.urls import path 
from . import views 

app_name = 'Faculty_app'

urlpatterns = [
    path('about-cse/', views.About_CSE_View.as_view(), name='about_cse'),
    path('faculty_members/', views.Faculty_members.as_view(), name='faculty_members'),
    path('faculty_profile/<int:pk>/', views.Faculty_profileView.as_view(), name='faculty_profile'),
    path('faculty_staffs/', views.Faculty_staffView.as_view(), name='faculty_staffs'),
    path('moderators/', views.Instructor_developer_moderatorView.as_view(), name='moderators'),
    path('developers/', views.DeveloperView.as_view(), name='developers'),
]

students/urls.py
from django.urls import path 
from . import views 

app_name = 'studentsapp'

urlpatterns = [
    path('ajax/skill-suggestions/', views.SkillSuggestionView.as_view(), name='skill-suggestions'),
    path('search_skills/', views.Search_skills.as_view(), name='search_skills'),
    path('all-students/', views.All_Students.as_view(), name='all_students'),
    path('profile/<slug:slug>/', views.Student_Profile.as_view(), name='student-profile'),
    path('update-profile/', views.Update_profile.as_view(), name='update_profile'),
    path('change-password/', views.Password_ChangeView.as_view(), name='change_password'),
    path('modify-certificates/', views.Delete_certificates.as_view(), name='modify_certificates'),
    path('search_blood/', views.Search_blood.as_view(), name='search_blood')
]

Faculty_app/models.py
from django.db import models
from django.core.files.base import ContentFile
from PIL import Image, ImageOps
from io import BytesIO

# Create your models here.

class About_CSE(models.Model):
    title1 = models.CharField(max_length=200, blank=True, null=True)
    body1 = models.TextField(max_length=2000, blank=True, null=True)
    title2 = models.CharField(max_length=200, blank=True, null=True)
    body2 = models.TextField(max_length=2000, blank=True, null=True)

    class Meta():
        verbose_name_plural = 'About CSE Dept. Head Message'
    def __str__(self):
        return f'{self.title1}'

class Faculty_profile(models.Model):
    photo = models.ImageField(upload_to='faculty_members', blank=True, null=True)
    name = models.CharField(max_length=255)
    designation = models.CharField(max_length=255)
    department_head = models.BooleanField(default=False)
    short_biography = models.CharField(max_length=1500, blank=True, null=True)
    research_interest = models.CharField(max_length=1500, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(null=True, blank=True)
    whatsapp = models.CharField(max_length=15, blank=True, null=True)
    linkedin = models.CharField(max_length=50, blank=True, null=True)
    github = models.CharField(max_length=50, blank=True, null=True)
    room_number = models.CharField(max_length=10, blank=True, null=True)
    sorting_priority = models.IntegerField(blank=True, null=True)

    class Meta():
        ordering = ['sorting_priority']
    
    def __str__(self):
        return f"{self.name} | {self.designation}"


    def save(self, *args, **kwargs):
        if self.photo:
            img = Image.open(self.photo)
            
            try:
                img = ImageOps.exif_transpose(img)  # This corrects orientation based on EXIF data
            except (ValueError, TypeError, AttributeError):
                # In case no EXIF data is available, we just continue
                pass

            if img.mode == "P":
                img = img.convert("RGBA")

            max_size = (400, 400)
            img.thumbnail(max_size, Image.Resampling.LANCZOS)

            img_io = BytesIO()
            img.save(img_io, format='PNG')  # Save as PNG (no need for quality setting)

            # Replace the image file with the compressed version
            self.photo = ContentFile(img_io.getvalue(), name=self.photo.name)

        super().save(*args, **kwargs)



class Research_and_publication(models.Model):
    faculty = models.ForeignKey(Faculty_profile, related_name='research_and_publications', on_delete=models.CASCADE)
    research_and_publication = models.TextField()

    class Meta():
        ordering = ['faculty__name']

    def __str__(self):
        return f"{self.faculty.name}"


class Academic_info(models.Model):
    faculty = models.ForeignKey(Faculty_profile, related_name='academic_info', on_delete=models.CASCADE)
    degree = models.CharField(max_length=220)
    institution = models.CharField(max_length=220)
    period = models.CharField(max_length=60, blank=True, null=True)

    class Meta():
        ordering = ['faculty__name', '-pk']

    def __str__(self):
        return f"{self.faculty.name} | {self.degree}"


class Experience(models.Model):
    faculty = models.ForeignKey(Faculty_profile, related_name='experiences', on_delete=models.CASCADE)
    institution_organization = models.CharField(max_length=60)
    position = models.CharField(max_length=220)
    job_role = models.CharField(max_length=220, blank=True, null=True)
    period = models.CharField(max_length=60, blank=True, null=True)

    class Meta():
        ordering = ['faculty__name', '-pk']

    def __str__(self):
        return f"{self.faculty.name} | {self.position} | {self.institution_organization}"
    

class Faculty_staff(models.Model):
    photo = models.ImageField(upload_to='faculty_staff', blank=True, null=True)
    name = models.CharField(max_length=255)
    designation = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(null=True, blank=True)
    whatsapp = models.CharField(max_length=15, blank=True, null=True)
    room_number = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return f"{self.name} | {self.designation}"
    


class Instructor_developer_moderator(models.Model):
    photo = models.ImageField(upload_to='inst_dev_moder', blank=True, null=True)
    name = models.CharField(max_length=255)
    designation = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(null=True, blank=True)
    whatsapp = models.CharField(max_length=15, blank=True, null=True)
    facebook = models.CharField(max_length=150, blank=True, null=True)
    linkedin = models.CharField(max_length=50, blank=True, null=True)
    github = models.CharField(max_length=50, blank=True, null=True)
    sorting_priority = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.name} | {self.designation}"
    
    def save(self, *args, **kwargs):
        if self.photo:
            img = Image.open(self.photo)
            
            try:
                img = ImageOps.exif_transpose(img)  # This corrects orientation based on EXIF data
            except (ValueError, TypeError, AttributeError):
                # In case no EXIF data is available, we just continue
                pass

            if img.mode == "P":
                img = img.convert("RGBA")

            max_size = (400, 400)
            img.thumbnail(max_size, Image.Resampling.LANCZOS)

            img_io = BytesIO()
            img.save(img_io, format='PNG')  # Save as PNG (no need for quality setting)

            # Replace the image file with the compressed version
            self.photo = ContentFile(img_io.getvalue(), name=self.photo.name)

        super().save(*args, **kwargs)

Faculty_app/forms.py
from django import forms 
from .models import Faculty_profile


class Faculty_profile_form(forms.ModelForm):
    class Meta:
        model = Faculty_profile
        fields = '__all__'

    short_biography = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'rows': 10,  
        'cols': 180,  
        'style': 'font-size: 16px; color: green;' 
    }))
    research_interest = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'rows': 10,  
        'cols': 180,  
        'style': 'font-size: 16px; color: green;' 
    }))
    
    sorting_priority = forms.IntegerField(
        required=False,
        help_text='Integer value to sort faculty profiles sequence while showing' )

Faculty_app/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, TemplateView


from .models import Faculty_profile, Faculty_staff, Instructor_developer_moderator, About_CSE

# Create your views here.


class About_CSE_View(TemplateView):
    template_name = 'about_cse.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['obj'] = About_CSE.objects.last()
        context['head_sir'] = Faculty_profile.objects.filter(department_head=True).first()
        return context



class Faculty_profileView(DetailView):
    model = Faculty_profile
    context_object_name = 'profile'
    template_name = 'faculty_profile.html'


class Faculty_members(ListView):
    model = Faculty_profile
    context_object_name = 'members'
    template_name = 'faculty_mambers.html'


class Faculty_staffView(ListView):
    model = Faculty_staff
    context_object_name = 'members'
    template_name = 'faculty_staff.html'
    

class Instructor_developer_moderatorView(ListView):
    model = Instructor_developer_moderator
    context_object_name = 'members'
    template_name = 'admin_moderators.html'


class DeveloperView(TemplateView):
    template_name = 'developers.html'

Faculty_app/templates/about_cse.html
{% extends 'base.html' %} {% load static %}
{% block title %} About CSE {% endblock %}
{% block body %}

<div class="container my-10">
    <h4 class="h4 text-center text-gray-600 pb-4 border-b-2 border-orange-500">{{ obj.title1 }}</h4>
    <div class="text-lg" data-aos="fade-up" data-aos-duration="1000" data-aos-mirror="true" data-aos-once="false">{{ obj.body1 | linebreaksbr }}</div>

    
    <div class="mt-8 flex flex-col lg:flex-row bg-white shadow-lg overflow-hidden">
        <!-- Left Section: Profile -->
        <div class="max-h-fit flex-shrink-0 lg:w-1/3 p-6 flex flex-col items-center border-1 border-sky-500"  data-aos="zoom-in" data-aos-duration="1000" data-aos-mirror="true" data-aos-once="false" data-aos-delay="200">
          <div class="w-40 h-40 rounded-full overflow-hidden border-4 border-gray-300 border-teal-500 mb-4 hover:scale-[1.3] duration-300">
            <img src="{{ head_sir.photo.url }}" alt="Md. Tarequl Islam" class="w-full h-full object-cover">
          </div>
          <h2 class="text-2xl font-bold text-red-500">{{ head_sir.name }}</h2>
          <p class="text-gray-700 text-xl font-medium">{{ head_sir.designation }}</p>
          <p class="text-gray-500 text-lg">Computer Science & Engineering</p>
        </div>
      
        <!-- Right Section: Message -->
        <div class="lg:w-2/3 lg:ml-3 px-6 border-1 border-gray-300">
          <h3 class="text-xl font-bold text-gray-700 py-3 border-b-2 border-orange-500">
            {{ obj.title2 }}
          </h3>
          <p class="text-lg text-gray-600 py-3" data-aos="fade-up" data-aos-duration="1300" data-aos-mirror="true" data-aos-once="false" data-aos-delay="200">
            {{ obj.body2 | linebreaksbr }}
          </p>
        </div>
      </div>
      

</div>


{% endblock %}

Faculty_app/templates/admin_moderators.html
{% extends 'base.html' %} {% load static %}
{% block title %} Instructor, Developer and Moderators {% endblock %}

{% block body %}


<div class="container my-20 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">


    {% for member in members %}
        <div class="flex items-center justify-center">
            <div class="max-w-sm w-full bg-white shadow-lg rounded-lg overflow-hidden transform hover:scale-105 transition-transform duration-300">
                <div class="relative h-40 bg-gradient-to-r from-sky-500 to-blue-400">
                    <div class="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1/2">
                        <img class="w-32 h-32 rounded-full border-4 border-white object-cover" src="{% if member.photo %}{{ member.photo.url}} {% else %} {% static 'images/profile.png' %}{% endif %}" alt="{{ member.name }}">
                    </div>
                </div>
                <div class="px-6 py-4 mt-12">
                    <h3 class="text-center text-2xl font-semibold text-gray-800 text-sky-500">{{ member.name }}</h3>
                    <p class="text-center text-gray-500 text-sm font-medium"> As {{ member.designation }}</p>
                    <!-- <p class="text-center text-gray-500 text-sm mt-1">{{ member.designation }}, Computer Science & Engineering<br>Khwaja Yunus Ali University</p> -->
                    <div class="mt-4 flex flex-col space-y-3">
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/telephone.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">{{ member.phone_number }}</span>
                        </div> 
                        {% if member.email %}
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/email-opened.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">{{ member.email }}</span>
                        </div>
                        {% endif %}

                        {% if member.whatsapp %}
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/whatsapp.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">{{ member.whatsapp }}</span>
                        </div>
                        {% endif %}

                        {% if member.linkedin %}
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/linkedin.png' %}" class="w-5 h-5" alt="">
                            <a href="{{ member.linkedin }}"><span class="text-green-600">{{ member.linkedin }}</span></a>
                        </div>
                        {% endif %}

                        {% if member.github %}
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/github.png' %}" class="w-5 h-5" alt="">
                            <a href="{{ member.github }}"><span class="text-green-600">{{ member.github }}</span></a>
                        </div>
                        {% endif %}

                        {% if member.facebook %}
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/facebook.png' %}" class="w-5 h-5" alt="">
                            <a href="{{ member.facebook }}"><span class="text-green-600">{{ member.facebook }}</span></a>
                        </div>
                        {% endif %}

                           
                    </div>
                </div>
                <div class="px-6 py-4 bg-indigo-100">
                    <a href="" class="block text-center text-indigo-500 font-medium text-sm hover:underline hover:text-indigo-600 transition-colors duration-300">
                    </a>
                </div>
            </div>
        </div>
    {% endfor %} 


</div>



{% endblock %}

Faculty_app/templates/developers.html
{% extends 'base.html' %} {% load static %}
{% block title %} Developers {% endblock %}

{% block body %}

<div class="my-10 p-8 text-3xl font-semibold text-indigo-600 text-center bg-sky-200 rounded-xl container">Developer and Instructor</div>

<div class="container my-20 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">

        <!--  Developer Card -->
    <div class="flex items-center justify-center">
        <div class="max-w-sm w-full bg-white shadow-lg rounded-lg overflow-hidden transform hover:scale-105 transition-transform duration-300">
            <div class="relative h-40 bg-gradient-to-r from-sky-500 to-blue-400">
                <div class="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1/2">
                    <img class="w-32 h-32 rounded-full border-4 border-white object-cover" src="{% static 'images/developer.jpg' %}" alt="Md. AL-Imran Sarker">
                </div>
            </div>
            <div class="px-6 py-4 mt-12">
                <h3 class="text-center text-2xl font-semibold text-gray-800 text-sky-500">Md. AL-Imran Sarker</h3>
                <p class="text-center text-gray-500 text-sm font-medium"> As Software Developer</p>
                <p class="text-center text-gray-500 text-sm mt-1">12th batch, Computer Science & Engineering<br>Khwaja Yunus Ali University</p>
                <div class="mt-4 flex flex-col space-y-3">
                    <div class="flex space-x-3">
                        <img src="{% static 'icons/telephone.png' %}" class="w-5 h-5" alt="">
                        <span class="text-green-600">01791-115371</span>
                    </div> 
                    <div class="flex space-x-3">
                        <img src="{% static 'icons/email-opened.png' %}" class="w-5 h-5" alt="">
                        <span class="text-green-600">imranthelegend12@gmail.com</span>
                    </div>
                    <div class="flex space-x-3">
                        <img src="{% static 'icons/whatsapp.png' %}" class="w-5 h-5" alt="">
                        <span class="text-green-600">01791-115371</span>
                    </div>
                    <!-- <div class="flex space-x-3">
                        <img src="{% static 'icons/linkedin.png' %}" class="w-5 h-5" alt="">
                        <a href="{{ member.linkedin }}"><span class="text-green-600">{{ member.linkedin }}</span></a>
                    </div>
                    <div class="flex space-x-3">
                        <img src="{% static 'icons/github.png' %}" class="w-5 h-5" alt="">
                        <a href="{{ member.github }}"><span class="text-green-600">{{ member.github }}</span></a>
                    </div> -->
                    <div class="flex space-x-3">
                        <img src="{% static 'icons/facebook.png' %}" class="w-5 h-5" alt="">
                        <a href="https://www.facebook.com/itsimransarker" target="_blank">
                            <span class="text-green-600">visit facebook profile</span>
                        </a>
                    </div>

                        
                </div>
            </div>
            <div class="px-6 py-4 bg-indigo-100">
                <a href="{% url 'studentsapp:student-profile' slug='137d1e1f-ca10-494c-81ac-5fbc32ac712b' %}" class="block text-center text-indigo-500 font-medium text-sm hover:underline hover:text-indigo-600 transition-colors duration-300">View Profile
                </a>
            </div>
        </div>
    </div>
    


        <!--  Project Instructor Card -->
        <div class="flex items-center justify-center">
            <div class="max-w-sm w-full bg-white shadow-lg rounded-lg overflow-hidden transform hover:scale-105 transition-transform duration-300">
                <div class="relative h-40 bg-gradient-to-r from-sky-500 to-blue-400">
                    <div class="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1/2">
                        <img class="w-32 h-32 rounded-full border-4 border-white object-cover" src="{% static 'images/rahat-sir.jpg' %}" alt="rahat-sir">
                    </div>
                </div>
                <div class="px-6 py-4 mt-12">
                    <h3 class="text-center text-2xl font-semibold text-gray-800 text-sky-500">Md. Rahat Khan</h3>
                    <p class="text-center text-gray-500 text-sm font-medium"> As Project Instructor</p>
                    <p class="text-center text-gray-500 text-sm mt-1">Lecturer, Computer Science & Engineering<br>Khwaja Yunus Ali University</p>
                    <div class="mt-4 flex flex-col space-y-3">
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/telephone.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">01521303383</span>
                        </div> 
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/email-opened.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">rahat.cse@kyau.edu.bd</span>
                        </div>
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/whatsapp.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">01521303383</span>
                        </div>
                        <!-- <div class="flex space-x-3">
                            <img src="{% static 'icons/linkedin.png' %}" class="w-5 h-5" alt="">
                            <a href="{{ member.linkedin }}"><span class="text-green-600">{{ member.linkedin }}</span></a>
                        </div>
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/github.png' %}" class="w-5 h-5" alt="">
                            <a href="{{ member.github }}"><span class="text-green-600">{{ member.github }}</span></a>
                        </div> -->
                        <!-- <div class="flex space-x-3">
                            <img src="{% static 'icons/facebook.png' %}" class="w-5 h-5" alt="">
                            <a href="https://www.facebook.com/itsimransarker" target="_blank">
                                <span class="text-green-600">visit facebook profile</span>
                            </a>
                        </div> -->
    
                            
                    </div>
                </div>
                <div class="px-6 py-4 bg-indigo-100">
                    <a href="{% url 'Faculty_app:faculty_profile' pk=8 %}" class="block text-center text-indigo-500 font-medium text-sm hover:underline hover:text-indigo-600 transition-colors duration-300">View Profile
                    </a>
                </div>
            </div>
        </div>

</div>



{% endblock %}

Faculty_app/templates/faculty_mambers.html
{% extends 'base.html' %} {% load static %}
{% block title %} Faculty members {% endblock %}

{% block body %}


<div class="container my-20 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">


    {% for member in members %}
        <div class="flex items-center justify-center bg-gray-100">
            <div class="max-w-sm w-full bg-white shadow-lg rounded-lg overflow-hidden transform hover:scale-105 transition-transform duration-300">
                <div class="relative h-40 bg-gradient-to-r from-sky-500 to-blue-400">
                    <div class="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1/2">
                        <img class="w-32 h-32 rounded-full border-4 border-white" src="{% if member.photo %}{{ member.photo.url}} {% else %} {% static 'images/profile.png' %}{% endif %}" alt="{{ member.name }}">
                    </div>
                </div>
                <div class="px-6 py-4 mt-12">
                    <h3 class="text-center text-2xl font-semibold text-gray-800 text-sky-500">{{ member.name }}</h3>
                    <p class="text-center text-gray-500 text-sm mt-1">{{ member.designation }}, Computer Science & Engineering<br>Khwaja Yunus Ali University</p>
                    <div class="mt-4 flex flex-col space-y-3">
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/telephone.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">{{ member.phone_number }}</span>
                        </div> 
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/email-opened.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">{{ member.email }}</span>
                        </div> 
                        <div class="flex items-center space-x-4 mt-4">
                            <img src="{% static 'icons/flat.png' %}" class="h-5 w-5" alt="Room Icon">
                            <span class="text-green-600">{{ member.room_number }}</span>
                        </div>
                           
                    </div>
                </div>
                <div class="px-6 py-4 bg-indigo-100">
                    <a href="{% url 'Faculty_app:faculty_profile' pk=member.pk %}" class="block text-center text-indigo-500 font-medium text-sm hover:underline hover:text-indigo-600 transition-colors duration-300">View Profile
                    </a>
                </div>
            </div>
        </div>

        
    {% endfor %} 


</div>



{% endblock %}

Faculty_app/templates/instructor_developer_moderator.html
{% extends 'base.html' %} {% load static %}
{% block title %} Instructor, Developer and Moderators {% endblock %}

{% block body %}


<div class="container my-20 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">


    {% for member in members %}
        <div class="flex items-center justify-center bg-gray-100">
            <div class="max-w-sm w-full bg-white shadow-lg rounded-lg overflow-hidden transform hover:scale-105 transition-transform duration-300">
                <div class="relative h-40 bg-gradient-to-r from-sky-500 to-blue-400">
                    <div class="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1/2">
                        <img class="w-32 h-32 rounded-full border-4 border-white object-cover" src="{% if member.photo %}{{ member.photo.url}} {% else %} {% static 'images/profile.png' %}{% endif %}" alt="{{ member.name }}">
                    </div>
                </div>
                <div class="px-6 py-4 mt-12">
                    <h3 class="text-center text-2xl font-semibold text-gray-800 text-sky-500">{{ member.name }}</h3>
                    <p class="text-center text-gray-500 text-sm font-medium"> As {{ member.designation }}</p>
                    <!-- <p class="text-center text-gray-500 text-sm mt-1">{{ member.designation }}, Computer Science & Engineering<br>Khwaja Yunus Ali University</p> -->
                    <div class="mt-4 flex flex-col space-y-3">
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/telephone.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">{{ member.phone_number }}</span>
                        </div> 
                        {% if member.email %}
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/email-opened.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">{{ member.email }}</span>
                        </div>
                        {% endif %}

                        {% if member.whatsapp %}
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/whatsapp.png' %}" class="w-5 h-5" alt="">
                            <span class="text-green-600">{{ member.whatsapp }}</span>
                        </div>
                        {% endif %}

                        {% if member.linkedin %}
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/linkedin.png' %}" class="w-5 h-5" alt="">
                            <a href="{{ member.linkedin }}"><span class="text-green-600">{{ member.linkedin }}</span></a>
                        </div>
                        {% endif %}

                        {% if member.github %}
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/github.png' %}" class="w-5 h-5" alt="">
                            <a href="{{ member.github }}"><span class="text-green-600">{{ member.github }}</span></a>
                        </div>
                        {% endif %}

                        {% if member.facebook %}
                        <div class="flex space-x-3">
                            <img src="{% static 'icons/facebook.png' %}" class="w-5 h-5" alt="">
                            <a href="{{ member.facebook }}"><span class="text-green-600">{{ member.facebook }}</span></a>
                        </div>
                        {% endif %}

                           
                    </div>
                </div>
                <div class="px-6 py-4 bg-indigo-100">
                    <a href="{% url 'Faculty_app:faculty_profile' pk=member.pk %}" class="block text-center text-indigo-500 font-medium text-sm hover:underline hover:text-indigo-600 transition-colors duration-300">
                    </a>
                </div>
            </div>
        </div>
    {% endfor %} 


</div>



{% endblock %}